[2023-05-10 08:20:47,710] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.clear_temp_files scheduled__2023-05-09T00:00:00+00:00 [queued]>
[2023-05-10 08:20:47,726] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.clear_temp_files scheduled__2023-05-09T00:00:00+00:00 [queued]>
[2023-05-10 08:20:47,728] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 08:20:47,730] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-10 08:20:47,732] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 08:20:47,750] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): clear_temp_files> on 2023-05-09 00:00:00+00:00
[2023-05-10 08:20:47,757] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-10 08:20:47,765] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'clear_temp_files', 'scheduled__2023-05-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmp_mqqbvn9', '--error-file', '/tmp/tmp8acxcwlo']
[2023-05-10 08:20:47,768] {standard_task_runner.py:80} INFO - Job 8: Subtask clear_temp_files
[2023-05-10 08:20:47,832] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.clear_temp_files scheduled__2023-05-09T00:00:00+00:00 [running]> on host dstreportdagscleartempfiles-0f531ecd6b0a4f1ab2a0ff480a83a6ea
[2023-05-10 08:20:48,765] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-10 08:20:48,775] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=clear_temp_files
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-09T00:00:00+00:00
[2023-05-10 08:20:48,776] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-10 08:20:48,779] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/bin/sh","-c","rm -rf /tmp/data/']
[2023-05-10 08:20:48,790] {subprocess.py:85} INFO - Output:
[2023-05-10 08:20:48,794] {subprocess.py:92} INFO - bash: line 1: /bin/sh,-c,rm: No such file or directory
[2023-05-10 08:20:48,795] {subprocess.py:96} INFO - Command exited with return code 127
[2023-05-10 08:20:48,804] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-05-10 08:20:48,808] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=clear_temp_files, execution_date=20230509T000000, start_date=20230510T082047, end_date=20230510T082048
[2023-05-10 08:20:48,820] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task clear_temp_files (Bash command failed. The command returned a non-zero exit code 127.; 22)
[2023-05-10 08:20:48,859] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-10 08:20:48,878] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
