[2023-05-10 09:10:58,408] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: get_attachment_from_dst_gmail.get_attachment scheduled__2023-05-09T00:00:00+00:00 [queued]>
[2023-05-10 09:10:58,417] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: get_attachment_from_dst_gmail.get_attachment scheduled__2023-05-09T00:00:00+00:00 [queued]>
[2023-05-10 09:10:58,418] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 09:10:58,419] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-10 09:10:58,420] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 09:10:58,430] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_attachment> on 2023-05-09 00:00:00+00:00
[2023-05-10 09:10:58,433] {standard_task_runner.py:52} INFO - Started process 18 to run task
[2023-05-10 09:10:58,437] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_attachment_from_dst_gmail', 'get_attachment', 'scheduled__2023-05-09T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_file_from_gmail.py', '--cfg-path', '/tmp/tmpm2rb_afo', '--error-file', '/tmp/tmprt0q759f']
[2023-05-10 09:10:58,438] {standard_task_runner.py:80} INFO - Job 35: Subtask get_attachment
[2023-05-10 09:10:58,493] {task_command.py:371} INFO - Running <TaskInstance: get_attachment_from_dst_gmail.get_attachment scheduled__2023-05-09T00:00:00+00:00 [running]> on host getattachmentfromdstgmailgetat-9096fdec23404b01ab12788f0ef0554c
[2023-05-10 09:10:59,434] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-10 09:10:59,446] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_attachment_from_dst_gmail
AIRFLOW_CTX_TASK_ID=get_attachment
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-09T00:00:00+00:00
[2023-05-10 09:10:59,696] {__init__.py:48} WARNING - file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/airflow/.local/lib/python3.8/site-packages/googleapiclient/discovery_cache/file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
[2023-05-10 09:11:01,395] {python.py:173} INFO - Done. Returned value was: b'Date,Time,Room No.,Name,Trn. Code,Description,Check No.,Currency,Debit,Credit,Cash ID,User Name,Supplement/Reference/Credit Card No.,Exp. Date,Receipt No.,01/05/23,12:32,08,Xie,Siyong,Mr.,3431,Photography & Videography,114407820230501043248,THB, 10,000.00, 0.00,997-OPERA-IFC,Room# 08 : CHECK# 1144078 [4013],Grand Total, 15,000.00, 0.00,\nDate,Time,Room No.,Name,Trn. Code,Description,Check No.,Currency,Debit,Credit,Cash ID,User Name,Supplement/Reference/Credit Card No.,Exp. Date,Receipt No.,01/05/23,12:34,48,*Ye,Fei,Mr.,3431,Photography & Videography,114407920230501043433,THB, 5,000.00, 0.00,997-OPERA-IFC,Room# 48 : CHECK# 1144079 [4013],Grand Total, 15,000.00, 0.00,\n'
[2023-05-10 09:11:01,422] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=get_attachment_from_dst_gmail, task_id=get_attachment, execution_date=20230509T000000, start_date=20230510T091058, end_date=20230510T091101
[2023-05-10 09:11:01,473] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-10 09:11:01,498] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
