[2023-05-10 08:20:48,877] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.clear_temp_files manual__2023-05-10T08:20:18.977791+00:00 [queued]>
[2023-05-10 08:20:48,887] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.clear_temp_files manual__2023-05-10T08:20:18.977791+00:00 [queued]>
[2023-05-10 08:20:48,888] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 08:20:48,888] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-10 08:20:48,889] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 08:20:48,901] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): clear_temp_files> on 2023-05-10 08:20:18.977791+00:00
[2023-05-10 08:20:48,905] {standard_task_runner.py:52} INFO - Started process 21 to run task
[2023-05-10 08:20:48,909] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'clear_temp_files', 'manual__2023-05-10T08:20:18.977791+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmph_r6fxk0', '--error-file', '/tmp/tmpdkxtdo_m']
[2023-05-10 08:20:48,914] {standard_task_runner.py:80} INFO - Job 9: Subtask clear_temp_files
[2023-05-10 08:20:48,981] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.clear_temp_files manual__2023-05-10T08:20:18.977791+00:00 [running]> on host dstreportdagscleartempfiles-c03a330bf849484a8c7ed0dabf44e008
[2023-05-10 08:20:49,799] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-10 08:20:49,808] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=clear_temp_files
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T08:20:18.977791+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-10T08:20:18.977791+00:00
[2023-05-10 08:20:49,810] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-10 08:20:49,811] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/bin/sh","-c","rm -rf /tmp/data/']
[2023-05-10 08:20:49,820] {subprocess.py:85} INFO - Output:
[2023-05-10 08:20:49,822] {subprocess.py:92} INFO - bash: line 1: /bin/sh,-c,rm: No such file or directory
[2023-05-10 08:20:49,823] {subprocess.py:96} INFO - Command exited with return code 127
[2023-05-10 08:20:49,833] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-05-10 08:20:49,836] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=clear_temp_files, execution_date=20230510T082018, start_date=20230510T082048, end_date=20230510T082049
[2023-05-10 08:20:49,851] {standard_task_runner.py:92} ERROR - Failed to execute job 9 for task clear_temp_files (Bash command failed. The command returned a non-zero exit code 127.; 21)
[2023-05-10 08:20:49,905] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-10 08:20:49,924] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
