[2023-05-09 16:43:41,468] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-09T16:43:30.946225+00:00 [queued]>
[2023-05-09 16:43:41,476] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-09T16:43:30.946225+00:00 [queued]>
[2023-05-09 16:43:41,477] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-09 16:43:41,478] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-09 16:43:41,479] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-09 16:43:41,488] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): generate_report> on 2023-05-09 16:43:30.946225+00:00
[2023-05-09 16:43:41,492] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-09 16:43:41,495] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'generate_report', 'manual__2023-05-09T16:43:30.946225+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmphqa_gf7l', '--error-file', '/tmp/tmpa9xmaz7g']
[2023-05-09 16:43:41,497] {standard_task_runner.py:80} INFO - Job 14: Subtask generate_report
[2023-05-09 16:43:41,550] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.generate_report manual__2023-05-09T16:43:30.946225+00:00 [running]> on host dstreportdagsgeneratereport-78a7bb7c11774828bc71de9309c6d47d
[2023-05-09 16:43:42,247] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-09 16:43:42,255] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=generate_report
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T16:43:30.946225+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-09T16:43:30.946225+00:00
[2023-05-09 16:43:42,257] {logging_mixin.py:115} INFO - data/*dst_revenue.csv
[2023-05-09 16:43:42,258] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dst_report_dags.py", line 79, in join_csv
    df_report = pd.concat(map(pd.read_csv, files), ignore_index=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2023-05-09 16:43:42,265] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=generate_report, execution_date=20230509T164330, start_date=20230509T164341, end_date=20230509T164342
[2023-05-09 16:43:42,283] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task generate_report (No objects to concatenate; 22)
[2023-05-09 16:43:42,310] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-09 16:43:42,326] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
