[2023-05-08 09:21:16,459] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.check_downloaded_files manual__2023-05-08T09:21:01.755173+00:00 [queued]>
[2023-05-08 09:21:16,475] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.check_downloaded_files manual__2023-05-08T09:21:01.755173+00:00 [queued]>
[2023-05-08 09:21:16,476] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-08 09:21:16,477] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-08 09:21:16,479] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-08 09:21:16,494] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): check_downloaded_files> on 2023-05-08 09:21:01.755173+00:00
[2023-05-08 09:21:16,499] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-08 09:21:16,504] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'check_downloaded_files', 'manual__2023-05-08T09:21:01.755173+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmp9kwta_ga', '--error-file', '/tmp/tmpufakqoe0']
[2023-05-08 09:21:16,507] {standard_task_runner.py:80} INFO - Job 61: Subtask check_downloaded_files
[2023-05-08 09:21:16,591] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.check_downloaded_files manual__2023-05-08T09:21:01.755173+00:00 [running]> on host dstreportdagscheckdownloadedfi-d385baffa0e44100bc96b2a7fb7792c3
[2023-05-08 09:21:17,749] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-08 09:21:17,762] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=check_downloaded_files
AIRFLOW_CTX_EXECUTION_DATE=2023-05-08T09:21:01.755173+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-08T09:21:01.755173+00:00
[2023-05-08 09:21:17,764] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-08 09:21:17,771] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'find data/q1/ -name "*.csv"']
[2023-05-08 09:21:17,783] {subprocess.py:85} INFO - Output:
[2023-05-08 09:21:17,788] {subprocess.py:92} INFO - find: ‘data/q1/’: No such file or directory
[2023-05-08 09:21:17,790] {subprocess.py:96} INFO - Command exited with return code 1
[2023-05-08 09:21:17,803] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-08 09:21:17,811] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=check_downloaded_files, execution_date=20230508T092101, start_date=20230508T092116, end_date=20230508T092117
[2023-05-08 09:21:17,839] {standard_task_runner.py:92} ERROR - Failed to execute job 61 for task check_downloaded_files (Bash command failed. The command returned a non-zero exit code 1.; 22)
[2023-05-08 09:21:17,889] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-08 09:21:17,935] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
