[2023-05-09 18:07:35,869] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-09T18:07:25.046205+00:00 [queued]>
[2023-05-09 18:07:35,876] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-09T18:07:25.046205+00:00 [queued]>
[2023-05-09 18:07:35,877] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-09 18:07:35,877] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-09 18:07:35,878] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-09 18:07:35,887] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): generate_report> on 2023-05-09 18:07:25.046205+00:00
[2023-05-09 18:07:35,891] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-09 18:07:35,894] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'generate_report', 'manual__2023-05-09T18:07:25.046205+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmpouuvj69r', '--error-file', '/tmp/tmprdl_mzdx']
[2023-05-09 18:07:35,896] {standard_task_runner.py:80} INFO - Job 24: Subtask generate_report
[2023-05-09 18:07:35,947] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.generate_report manual__2023-05-09T18:07:25.046205+00:00 [running]> on host dstreportdagsgeneratereport-aa7f50790c3b4e27a734856cadd93293
[2023-05-09 18:07:36,722] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-09 18:07:36,732] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=generate_report
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T18:07:25.046205+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-09T18:07:25.046205+00:00
[2023-05-09 18:07:36,733] {logging_mixin.py:115} INFO - data/*dst_revenue.csv
[2023-05-09 18:07:36,734] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dst_report_dags.py", line 83, in join_csv
    df_report = pd.concat(map(pd.read_csv, files), ignore_index=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2023-05-09 18:07:36,740] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=generate_report, execution_date=20230509T180725, start_date=20230509T180735, end_date=20230509T180736
[2023-05-09 18:07:36,754] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task generate_report (No objects to concatenate; 22)
[2023-05-09 18:07:36,793] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-09 18:07:36,812] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
