[2023-05-08 10:18:02,648] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-08T10:17:48.533176+00:00 [queued]>
[2023-05-08 10:18:02,661] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-08T10:17:48.533176+00:00 [queued]>
[2023-05-08 10:18:02,662] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-08 10:18:02,663] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-08 10:18:02,665] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-08 10:18:02,681] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): generate_report> on 2023-05-08 10:17:48.533176+00:00
[2023-05-08 10:18:02,686] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-08 10:18:02,692] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'generate_report', 'manual__2023-05-08T10:17:48.533176+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmp_x99qe81', '--error-file', '/tmp/tmpxtpji_7w']
[2023-05-08 10:18:02,694] {standard_task_runner.py:80} INFO - Job 70: Subtask generate_report
[2023-05-08 10:18:02,778] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.generate_report manual__2023-05-08T10:17:48.533176+00:00 [running]> on host dstreportdagsgeneratereport-e57a3ef4d96c4743999db707bb32960a
[2023-05-08 10:18:03,941] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-08 10:18:03,957] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=generate_report
AIRFLOW_CTX_EXECUTION_DATE=2023-05-08T10:17:48.533176+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-08T10:17:48.533176+00:00
[2023-05-08 10:18:03,981] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dst_report_dags.py", line 83, in join_csv
    with pd.ExcelWriter(f'{year}_q{quarter}_dst_report.xlsx') as writer:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 49, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2023-05-08 10:18:03,991] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=generate_report, execution_date=20230508T101748, start_date=20230508T101802, end_date=20230508T101803
[2023-05-08 10:18:04,007] {standard_task_runner.py:92} ERROR - Failed to execute job 70 for task generate_report (No module named 'openpyxl'; 22)
[2023-05-08 10:18:04,072] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-08 10:18:04,100] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
