[2023-05-10 08:47:50,745] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.clear_temp_files manual__2023-05-10T08:42:34.801630+00:00 [queued]>
[2023-05-10 08:47:50,753] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.clear_temp_files manual__2023-05-10T08:42:34.801630+00:00 [queued]>
[2023-05-10 08:47:50,754] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 08:47:50,754] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-05-10 08:47:50,755] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 08:47:50,765] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): clear_temp_files> on 2023-05-10 08:42:34.801630+00:00
[2023-05-10 08:47:50,768] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-10 08:47:50,772] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'clear_temp_files', 'manual__2023-05-10T08:42:34.801630+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmpo43ziub3', '--error-file', '/tmp/tmpz7mo9zp7']
[2023-05-10 08:47:50,774] {standard_task_runner.py:80} INFO - Job 24: Subtask clear_temp_files
[2023-05-10 08:47:50,835] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.clear_temp_files manual__2023-05-10T08:42:34.801630+00:00 [running]> on host dstreportdagscleartempfiles-e13dae7a748b4e3daf6545c74a6ebf2e
[2023-05-10 08:47:51,613] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-10 08:47:51,623] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=clear_temp_files
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T08:42:34.801630+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-10T08:42:34.801630+00:00
[2023-05-10 08:47:51,624] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-10 08:47:51,625] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/bin/sh","-c","rm -rf /foo/files/']
[2023-05-10 08:47:51,633] {subprocess.py:85} INFO - Output:
[2023-05-10 08:47:51,635] {subprocess.py:92} INFO - bash: line 1: /bin/sh,-c,rm: No such file or directory
[2023-05-10 08:47:51,636] {subprocess.py:96} INFO - Command exited with return code 127
[2023-05-10 08:47:51,645] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-05-10 08:47:51,649] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=clear_temp_files, execution_date=20230510T084234, start_date=20230510T084750, end_date=20230510T084751
[2023-05-10 08:47:51,661] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task clear_temp_files (Bash command failed. The command returned a non-zero exit code 127.; 22)
[2023-05-10 08:47:51,722] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-10 08:47:51,741] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
