[2023-05-09 21:08:45,470] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.get_file_from_gcs manual__2023-05-09T21:08:38.034346+00:00 [queued]>
[2023-05-09 21:08:45,482] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.get_file_from_gcs manual__2023-05-09T21:08:38.034346+00:00 [queued]>
[2023-05-09 21:08:45,483] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-09 21:08:45,484] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-09 21:08:45,485] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-09 21:08:45,500] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_file_from_gcs> on 2023-05-09 21:08:38.034346+00:00
[2023-05-09 21:08:45,505] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-09 21:08:45,516] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'get_file_from_gcs', 'manual__2023-05-09T21:08:38.034346+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmpc7sr7wpc', '--error-file', '/tmp/tmpe_rpszqn']
[2023-05-09 21:08:45,519] {standard_task_runner.py:80} INFO - Job 10: Subtask get_file_from_gcs
[2023-05-09 21:08:45,617] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.get_file_from_gcs manual__2023-05-09T21:08:38.034346+00:00 [running]> on host dstreportdagsgetfilefromgcs-cd1dc76425d94308827300d59ad63619
[2023-05-09 21:08:47,016] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-09 21:08:47,030] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=get_file_from_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T21:08:38.034346+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-09T21:08:38.034346+00:00
[2023-05-09 21:08:47,788] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dst_report_dags.py", line 42, in get_file_from_gcs
    os.makedirs(directory)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/foo/'
[2023-05-09 21:08:47,798] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=get_file_from_gcs, execution_date=20230509T210838, start_date=20230509T210845, end_date=20230509T210847
[2023-05-09 21:08:47,814] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task get_file_from_gcs ([Errno 13] Permission denied: '/foo/'; 22)
[2023-05-09 21:08:47,882] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-09 21:08:47,923] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
