[2023-05-08 10:23:19,958] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-08T10:23:04.810966+00:00 [queued]>
[2023-05-08 10:23:19,971] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dst_report_dags.generate_report manual__2023-05-08T10:23:04.810966+00:00 [queued]>
[2023-05-08 10:23:19,972] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-08 10:23:19,974] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-08 10:23:19,975] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-08 10:23:19,994] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): generate_report> on 2023-05-08 10:23:04.810966+00:00
[2023-05-08 10:23:19,999] {standard_task_runner.py:52} INFO - Started process 22 to run task
[2023-05-08 10:23:20,003] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dst_report_dags', 'generate_report', 'manual__2023-05-08T10:23:04.810966+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dst_report_dags.py', '--cfg-path', '/tmp/tmpmpi2r67r', '--error-file', '/tmp/tmpyc9b54dd']
[2023-05-08 10:23:20,006] {standard_task_runner.py:80} INFO - Job 75: Subtask generate_report
[2023-05-08 10:23:20,081] {task_command.py:371} INFO - Running <TaskInstance: dst_report_dags.generate_report manual__2023-05-08T10:23:04.810966+00:00 [running]> on host dstreportdagsgeneratereport-2f25322548f94bdf9fd2e708cc8f393d
[2023-05-08 10:23:21,221] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-08 10:23:21,235] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dst_report_dags
AIRFLOW_CTX_TASK_ID=generate_report
AIRFLOW_CTX_EXECUTION_DATE=2023-05-08T10:23:04.810966+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-08T10:23:04.810966+00:00
[2023-05-08 10:23:21,247] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dst_report_dags.py", line 83, in join_csv
    with pd.ExcelWriter(f'{year}_q{quarter}_dst_report.xlsx') as writer:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 49, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2023-05-08 10:23:21,257] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dst_report_dags, task_id=generate_report, execution_date=20230508T102304, start_date=20230508T102319, end_date=20230508T102321
[2023-05-08 10:23:21,271] {standard_task_runner.py:92} ERROR - Failed to execute job 75 for task generate_report (No module named 'openpyxl'; 22)
[2023-05-08 10:23:21,305] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-08 10:23:21,330] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
